[project]
name = "apscheduler-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.11.1",
]

[dependency-groups]
dev = [
    "ruff>=0.12.7",
]
